Use lua_pushinteger instead of lua_pushunsigned
kaworu/lua-sysctl pull request #8
Opened 2021-03-01 01:01 UTC by samm-git

Use lua_pushinteger instead of lua_pushunsigned to make it compatible with lua 53+. Tested on LUA 5.3 and LUA 5.4

2021-03-04 14:35 UTC, kaworu requested changes
Thank you @samm-git for the PR! Overall LGTM but I have a couple of comments.

2021-03-04 14:35 UTC, kaworu commented on Makefile
> +CFLAGS  += -Wall -Wextra -fPIC `pkg-config --cflags ${LUA_VER}`
This is not working as-is for me:
```console
% make
install -m 755 -d build
cc -O2 -pipe -Wall -Wextra -fPIC `pkg-config --cflags 5.2` -o build/sysctl.so  -shared -Wl,-soname,lua_sysctl src/lua_sysctl.c
Package 5.2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `5.2.pc'
to the PKG_CONFIG_PATH environment variable
Package '5.2', required by 'virtual:world', not found
src/lua_sysctl.c:60:10: fatal error: 'lua.h' file not found
#include "lua.h"
         ^~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/alex/github/lua-sysctl
```

```suggestion
CFLAGS  += -Wall -Wextra -fPIC `pkg-config --cflags lua-${LUA_VER}`
```

2021-03-04 14:35 UTC, kaworu commented on src/lua_sysctl.c
> +				        lua_pushinteger(L, (lua_Integer)(umv));
Please indent with tab in order to be consistent with the rest of the file. More importantly, the check line 517 need to be adapted (to check against `sizeof(lua_Integer)` instead of `sizeof(lua_Unsigned)`).

2021-03-05 20:37 UTC, samm-git commented
Thank you for feedback (should never do a blind patch in the gh editor again ;-)). Requested changes addressed.

2021-03-06 12:48 UTC, kaworu requested changes
Thanks for the quick follow-up @samm-git! I realized that one of my suggestion was wrong, sorry for that. Would you mind updating the PR once again? Thanks a lot.

2021-03-06 12:48 UTC, kaworu commented on src/lua_sysctl.c
> +				if (intlen > sizeof(lua_Integer))
Now that I think of it, this condition is incorrect.

An `unsigned int` may hold a value that cannot be represented as a `signed int` (e.g. `INT_MAX + 1`). Thus, checking the representation length doesn't guarantee the cast from `unsigned int` to `signed int` is safe. Instead, the value should be checked:
```suggestion
				if (umv > LUA_MAXINTEGER)
```

Unfortunately, lua 5.2 doesn't define `LUA_MAXINTEGER` so we have to add some compat goo after the lua includes:
```c
/*
 * lua 5.3+ define LUA_MAXINTEGER, but lua 5.2 does not. See
 * https://www.lua.org/manual/5.2/manual.html#lua_Integer
 */
#ifndef LUA_MAXINTEGER
#define LUA_MAXINTEGER  PTRDIFF_MAX
#endif
```

2021-03-18 21:15 UTC, samm-git commented
PR updated, thank you for review and suggested.

2021-03-19 20:21 UTC, kaworu approved these changes
Thank you, LGTM!

2021-03-19 20:21 UTC, merged

2021-03-20 05:57 UTC, kraileth commented
Thanks for the contribution, @samm-git!
@kaworu Thank you for merging - would you consider making a new release? I'd like to update my port to support multiple Lua versions. If you think it's not worth a release, I'll put the required patches into the port. But of course handling things upstream is always better.

2021-03-20 14:25 UTC, kaworu commented
@kraileth Sure thing, I've just [released v2.1](https://github.com/kaworu/lua-sysctl/releases/tag/v2.1). Thanks a lot for maintaining the port!

2021-03-20 16:22 UTC, kraileth commented
My pleasure! Updated it in Ravenports. Should be available as packages (variants for Lua 5.2, 5.3 and 5.4) for both FreeBSD and DragonFly BSD when the next package build run is done. Will wait a while to see if the FreeBSD ports maintainer picks up the new version and ping him otherwise.

BTW: Would you also take a trivial patch to support DragonFly BSD out of the box? If so I can open a PR for it.

2021-03-20 19:09 UTC, kaworu commented
> BTW: Would you also take a trivial patch to support DragonFly BSD out of the box? If so I can open a PR for it.

I'm definitely open to the idea, my issue is that I don't have a DragonFlyBSD box to test out patches and am unaware of any CI plateform (i.e. Travis-CI, GitHub actions etc.) supporting DragonFlyBSD. Can you start by opening an issue to move the discussion there?

2021-03-20 21:50 UTC, kraileth commented
@kaworu Opened PR #10 for it.